# Generated by Django 5.0.4 on 2024-05-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='code')),
                ('is_valid_from', models.DateTimeField(verbose_name='is valid from')),
                ('is_valid_until', models.DateTimeField(verbose_name='is valid until')),
                ('discount', models.PositiveIntegerField(verbose_name='discount')),
                ('max_usage', models.PositiveIntegerField(verbose_name='max usage')),
                ('active', models.BooleanField(verbose_name='active')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
    ]
